title: Ethical Assurance
email: cburr@turing.ac.uk

# description: 
copyright: Ethics Team, Alan Turing Institute, 2022

# Build settings
plugins:
  - premonition
  - jekyll-feed
  - jekyll-glossary_tooltip
  - jekyll/scholar
  - jekyll_picture_tag

scholar:
  style: apa
  locale: en
  source: _bibliography/
  bibliography: bibliography.bib
  allow_locale_overrides: true

collections:
  glossary:
    output: true
  authors:
    output: true
  guides:
    output: true
    order:
      - what-is-ethical-assurance.md
      - why-is-ethical-assurance-important.md
      - how-to-build-an-ethical-assurance-case.md
      - the-project-lifecycle.md

premonition:
  types:
    list:
      meta:
        fa-icon: fa-list

sass:
  load_paths:
    - _sass

markdown: kramdown
highlighter: rouge

premonition:
  types:
    list:
      meta:
        fa-icon: fa-list

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_authors"
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: "_guides"
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: "**/*"
    values:
      layout: "default"
